services:
  api:
    image: api-uni:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_CONN: "postgresql://hoodie:kuuli@postgres:5432/uni"
      HEADLESS: "false"
      DISPLAY: $DISPLAY  # Allow container to use host display
      QT_X11_NO_MITSHM: "1"  # Prevent shared memory errors
      SELECTORS_PATH: "app/selectors"
    stop_signal: SIGKILL
    depends_on:
      - postgres
    volumes:
      - ./app:/api-uni/app
      - /tmp/.X11-unix:/tmp/.X11-unix  # Share X11 socket with container

  postgres:
    image: postgres-uni:latest
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DB_USER: hoodie
      DB_PASSWORD: kuuli
      DB_NAME: uni
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-contents:/var/lib/postgresql/data

volumes:
  db-contents:
